"""Add album publishing fields (is_locked, published_at)

Revision ID: 4d5aa478f518
Revises: 91ca4bf006d8
Create Date: 2026-06-18 09:45:50.680669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5aa478f518'
down_revision: Union[str, None] = '91ca4bf006d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.add_column('albums', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_albums_status'), 'albums', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_status'), table_name='albums')
    op.drop_column('albums', 'published_at')
    op.drop_column('albums', 'is_locked')
    # ### end Alembic commands ###
